### ISSUE TITLE
picking `ref` from component's props is not allowed

### ISSUE THREAD

**Issue by Skona27** [kripod/react-polymorphic-box#14] opened 2020-07-16 12:29 UTC
## Description

Picking `ref` from component's props produces an error. Picking it is necessary to assign proper type to `innerRef`.

Error:
```
Warning: [object Object]: `ref` is not a prop. Trying to access it will result in `undefined` being returned. 
If you need to access the same value within the child component, you should pass it as a different prop.
(https://fb.me/react-special-props)
```

## Reproduction

My code is similar to example code from `Readme.md` section on how to pass `ref`:

```ts
export const Box = React.forwardRef(
  <E extends React.ElementType = typeof defaultElement>(
    { ref, ...restProps }: BoxProps<E>,
    innerRef: typeof ref
  ) => {
    return <StyledBox ref={innerRef} as={defaultElement} {...restProps} />;
  }
) as <E extends React.ElementType = typeof defaultElement>(
  props: BoxProps<E>
) => JSX.Element;
```
## Expected behavior

`innerRef` should be somehow typed without picking `ref` from component's props

## Environment

I am using Next.js `9.4.4` and React `16.13.1`

**Comment by kripod** [comment] 2020-07-16 15:13
Thank you for reporting! Could you please provide a CodeSandbox example of what’s wrong? I suspect that `StyledBox` may have an issue on its own, possibly not caused by react-polymorhpic-box.

**Comment by rajatsharma** [comment] 2020-07-16 16:01
Facing the same issue, I am doing this to fix this. I am not sure if it's the right way

```typescript
const Box = React.forwardRef(
  <E extends ElementType = typeof DEFAULT_ELEMENT>({
    ...props
  }: BoxProps<E>, innerRef: E extends Element ? React.Ref<E> : React.Ref<never>) => {
    return (
      <PolymorphicBox
        as={DEFAULT_ELEMENT}
        ref={innerRef}
        {...props}
      />
    )
  }
) as <E extends React.ElementType = typeof DEFAULT_ELEMENT>(
  props: BoxProps<E>,
) => JSX.Element
```

**Comment by rajatsharma** [comment] 2020-07-16 16:21
Here's the CodeSandbox for my example: https://codesandbox.io/s/cocky-lehmann-2iy2t?file=/src/Box.tsx

**Comment by Skona27** [comment] 2020-07-16 16:45
CodeSandbox example created by @rajatsharma is also valid for my case. It looks like it is not problem with what is beeing rendered in `Box` component, but almost likely it's an issue with destructuring `ref` from `BoxProps`

**Comment by kripod** [comment] 2020-07-16 17:24
Refs should be assigned to a variable instantiated with React's [`useRef`](https://reactjs.org/docs/hooks-reference.html#useref) _(instead of using the setter of `useState`)._ I've [fixed your example](https://codesandbox.io/s/dark-wave-dz1z2?file=/src/App.tsx) and also created [a new playground](https://codesandbox.io/s/hungry-firefly-2l81h?file=/src/App.tsx), based upon the readme's instructions.

Please get back to me if any of you encounter another issue.

**Closed as completed by kripod** 2020-07-16 17:24 UTC
Labels: bug

**Comment by kripod** [comment] 2020-07-16 17:35
I've added the aforementioned example to [the bottom of the readme](https://github.com/kripod/react-polymorphic-box/blob/d06b7354a2169c4ffd3a8ff272bfa007fc57698a/README.md#forwarding-refs). Thanks again for raising these concerns!

**Comment by rajatsharma** [comment] 2020-07-16 17:55
The issue is still there, even if you use `useRef`. If you open the Console tab in your [created playground](https://codesandbox.io/s/hungry-firefly-2l81h?file=/src/App.tsx), you'll see this error:

```
Warning: [object Object]: `ref` is not a prop. Trying to access it will result in `undefined` being returned. 
If you need to access the same value within the child component, you should pass it as a different prop.
(https://fb.me/react-special-props)
```

**Comment by kripod** [comment] 2020-07-16 19:59
I'm sorry, CodeSandbox didn't show the error for me. It turns out that the `ref` prop shall not be destructured, but kept inside `...restProps`, as follows:

```diff
import { Box } from "react-polymorphic-box";

export const Heading = React.forwardRef(
  <E extends React.ElementType = typeof defaultElement>(
+    { color, style, ...restProps }: HeadingProps<E>,
+    innerRef: typeof restProps.ref
-    { ref, color, style, ...restProps }: HeadingProps<E>,
-    innerRef: typeof ref
  ) => {
    return (
      <Box
-       ref={innerRef}
        as={defaultElement}
        style={{ color, ...style }}
        {...restProps}
+       ref={innerRef}
      />
    );
  }
) as <E extends React.ElementType = typeof defaultElement>(
  props: HeadingProps<E>
) => JSX.Element;
```

I've updated the readme and my playground to reflect these changes. Also, I've [fixed the example](https://codesandbox.io/s/recursing-wave-y40b6?file=/src/Box.tsx) of @rajatsharma again.

**Comment by kripod** [comment] 2020-07-16 20:04
@all-contributors please add @Skona27 for bugs!
@all-contributors please add @rajatsharma for bugs!

**Comment by kripod** [comment] 2020-07-16 20:05
@all-contributors please add @Skona27 for bug reporting!
